collections:
  type: list
  schema:
    type: dict
    schema:
      name:
        type: string
        required: false
      root:
        type: string
        required: true
      repos:
        type: list
        schema:
          type: dict
          schema:
            url:
              type: string
              required: true
            branch:
              type: string
              nullable: true
              required: false
            depth:
              type: integer
              nullable: true
              required: false
            dest:
              type: string
              required: false
