[tool.black]
line-length = 88
target-version = ['py38']

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, E501"
exclude = "venv, .git, __pycache__, .eggs, *.egg"

[tool.isort]
profile = "black"

[tool.pytest]
addopts = [
    "--cov=src",
    "--cov-report=html",
    "--cov-report=term",
    "--verbose"
]

