# Run a basic Python CI using tox in github actions
#
# Based on: https://github.com/ymyzk/tox-gh-actions#usage
#
# P. Gierz

name: Basic Check
on:
  - push
  - pull_request
            
jobs:
  main_test:
    name: Setup Nox
    uses: daisylb/setup-nox@v2.1.0
